/**
 * Author: Professor Krasso
 * Updated by: Caleb Goforth
 * Date: 7 August 2024
 * File: app.js
 * Description: Application setup. Autogenerated using Express generator.
 */

'use strict';

// Core modules and middleware
const express = require('express');
const cookieParser = require('cookie-parser');
const logger = require('morgan');
const { notFoundHandler, errorHandler } = require('./utils/error-handler');

// Routers
const indexRouter = require('./routes/index');
const usersRouter = require('./routes/users');
const securityRouter = require('./routes/security');
const dashboardRouter = require('./routes/dashboard');
const salesReportsRouter = require('./routes/reports/sales');
const agentPerformanceReportsRouter = require('./routes/reports/agent-performance');
const customerFeedbackReportsRouter = require('./routes/reports/customer-feedback');

// App instance
const app = express();

// CORS configuration
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  next();
});

// Middleware
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Routes
app.use('/api', indexRouter);
app.use('/api/users', usersRouter);
app.use('/api/security', securityRouter);
app.use('/api/dashboard', dashboardRouter);
app.use('/api/reports/sales', salesReportsRouter);
app.use('/api/reports/agent-performance', agentPerformanceReportsRouter);
app.use('/api/reports/customer-feedback', customerFeedbackReportsRouter);

// Error handling
app.use(notFoundHandler);
app.use(errorHandler);

// Export app
module.exports = app;
